trainer:
  accumulate_grad_batches: 4
model:
  init_args:
    seg_arch: Unetpp
    seg_kwargs:
      encoder_name: tu-tf_efficientnetv2_m.in21k_ft_in1k
      encoder_weights: null
      in_channels: 1
      classes: 24
      encoder_depth: 5
data:
  init_args:
    batch_size: 8